swagger: '2.0'
info:
  title: Argent Bank transaction API documentation
  description: Contains all available API endpoints for the future transactions feature
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions/all:
    get:
      tags:
        - Transactions
      summary: read all transactions
      description: API to get all transactions of the user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: All transactions successfully retrived
          schema:
            allOf:
            - $ref: '#/definitions/ApiResponse'
            - type: object
              properties:
                body:
                  type: object
                  properties:
                    transactions:
                      type: array
                      description: the transactions corresponding to the user
                      items:
                        $ref: "#/definitions/TransactionReadOnly"
        '400':
          description: Invalid Fields
          schema:
            $ref: "#/definitions/ApiResponse"
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ApiResponse"
        '500':
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiResponse"
  
  /user/transactions/transaction:
    get:
      tags:
        - Transactions
      security:
        - Bearer: []
      summary: read a transaction
      description: API to get one transaction according transactionId parameter
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: id of the transaction to retrieve
          required: true
          schema: 
            type: object
            properties:
              id:
                type: string
                description: the id of the transaction
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successfully retrived
          schema:
            allOf:
            - $ref: '#/definitions/ApiResponse'
            - type: object
              properties:
                body:
                  $ref: "#/definitions/TransactionFull"
        '400':
          description: Invalid Fields
          schema:
            $ref: "#/definitions/ApiResponse"
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ApiResponse"
        '500':
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiResponse"
      
    put:
      tags:
        - Transactions
      security:
        - Bearer: []
      summary: update a transaction
      description: API to put new details to a transaction according transactionId parameter
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: id and attributes for the update of the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionEditable'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successfully updated
          schema:
            allOf:
            - $ref: '#/definitions/ApiResponse'
            - type: object
              properties:
                body:
                  $ref: "#/definitions/TransactionFull"
        '400':
          description: Invalid Fields
          schema:
            $ref: "#/definitions/ApiResponse"
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ApiResponse"
        '500':
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiResponse"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
  TransactionFull:
    allOf:
    - $ref: "#/definitions/TransactionReadOnly"
    - $ref: "#/definitions/TransactionEditable"
  TransactionReadOnly:
    type: object
    required:
    - id
    - date
    - name
    - amount
    - type
    properties:
      id:
        type: string
        description: the autogenerated id for the transaction
        example: 87d5f4sd5f4s15df4
      date:
        type: string
        format: date-time
        description: date of the transaction
        example: '2018-09-22T15:00:00'
      description:
        type: string
        description: name of the transaction
        example: Golden Sun Bakery
      amount:
        type: number
        format: float
        description: amount of the transaction
        example: 15.21
      type:
        type: string
        description: type of the transaction (electronic, check, credit card, ...)
        enum:
        - credit card
        - electronic
        - check
        - cash withdrawal
        - bank transfer
        - fees
  
  TransactionEditable:
    type: object
    required:
    - id
    properties:
      id:
        type: string
        description: the autogenerated id for the transaction
        example: 87d5f4sd5f4s15df4
      category:
        type: string
        description: category corresponding to the transaction
        example: food
      notes:
        type: string
        description: free field to write some notes about the transaction
        example: lunch expenses
        